---
- name: start libvirt daemon
  service:
    name: libvirtd
    state: started

- virt_net:
    command: define
    name: ocp
    xml: "{{lookup('file', 'files/{{ ocp.version }}/conf/libvirtd.nat-ocp.xml')}}"

- virt_net:
    command: create
    name: ocp
    state: active
