---
- name: start libvirt daemon
  service:
    name: libvirtd
    state: started

- name: check if ocp nat already exists
  virt_net:
    command: list_nets
  register: all_nets

- name: destroy old ocp nat
  virt_net:
    command: destroy
    name: ocp
  when: 'ocp in all_nets.list_nets'

- name: undefine old ocp nat
  virt_net:
    command: undefine
    name: ocp
  when: 'ocp in all_nets.list_nets'

- name: define ocp nat
  virt_net:
    command: define
    name: ocp
    xml: "{{lookup('file', 'files/{{ ocp.version }}/conf/libvirtd.nat-ocp.xml')}}"

- name: start ocp nat
  virt_net:
    command: create
    name: ocp
    state: active
