---
- name: make files dir
  file:
    path: "{{ files.base }}"
    state: directory

- name: make rocky files dir
  file:
    path: "{{ files.rocky }}"
    state: directory
  tags: nfs

- name: make files/clients dir
  file:
    path: "{{ files.base }}/clients"
    state: directory

- name: make files/dependencies dir
  file:
    path: "{{ files.base }}/dependencies"
    state: directory

- name: make files/conf dir
  file:
    path: "{{ files.base }}/conf"
    state: directory
